apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: mysql
spec:
  ports:
    # Accept traffic sent to port 
    - name: tcp
      port: 3306
      targetPort: 3306
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: mysql
    
  type: ClusterIP  
